name: Continuous Integration - Folder 02

on:
  push:
    branches:
      - main
    paths:
      - '02/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r 02/requirements.txt

      - name: Run task A
        working-directory: 02/A
        run: python task_A.py

      - name: Run task B
        working-directory: 02/B
        run: python task_B.py

      - name: Run task C
        working-directory: 02/C
        run: python task_C.py

      - name: Run task D
        working-directory: 02/D
        run: python task_D.py
